# Generated by Django 5.0 on 2023-12-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_question_remove_email_user_remove_user_tasks_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='publication_date',
        ),
    ]
