# Generated by Django 5.0 on 2023-12-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_remove_question_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
