# Generated by Django 5.0 on 2023-12-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_choice_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(default=None, max_length=3000),
            preserve_default=False,
        ),
    ]
